#ifndef RELAY_CONSTANTS_H
#define RELAY_CONSTANTS_H

#define DHCP_SERVER_PORT 1067
#define DHCP_CLIENT_PORT 1068
#define DHCP_RELAY_PORT 1069
#define IP_SERVER_IDENTIFIER "192.168.1.100" // Dirección IP del servidor.
#define BUFFER_SIZE 576

#endif 
